apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasure-ricardo
  namespace: treasure-hunt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasure-ricardo
  template:
    metadata:
      labels:
        app: treasure-ricardo
    spec:
      containers:
        - name: web
          image: docker.io/ricardoerazo306/treasure-new:latest
          ports:
            - containerPort: 80
          env:
            - name: TITLE
              value: "Treasure Hunt — Ricardo"
            - name: STUDENT
              value: "Ricardo Erazo"
            - name: SALT
              value: "DS3univalle"
            - name: KEY_HASH
              value: "b42e6b5522fc27b366b9e6e65555a377ef1f9d061b8b4c8cddc13c74d9bbad94"
            - name: CLUE
              valueFrom:
                secretKeyRef:
                  name: ricardo-clue
                  key: CLUE
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-ricardo
  namespace: treasure-hunt
spec:
  selector:
    app: treasure-ricardo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32380   # (opcional) fija uno en el rango 30000–32767
  type: NodePort